{{- if and .Values.apisix.enabled .Values.apisix.gatewayProxy.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.apisix.gatewayProxy.controlPlane.adminKeySecret.name }}
  namespace: {{ .Values.apisix.gatewayProxy.namespace }}
type: Opaque
stringData:
  {{ .Values.apisix.gatewayProxy.controlPlane.adminKeySecret.key }}: {{ .Values.apisix.gatewayProxy.controlPlane.adminKeySecret.value | quote }}
{{- end }}

